bcgov/bc-emli-pin-mgmt-be

- README.md
Added lifecycle badge and Apache 2 license to readme
> Lifecycle badge

- .gitignore
- LICENSE
- package.json
- tsconfig.json
Contains npm package setup, tsconfig as well as licenses for all used libraries + node.js
> Backend setup

- Dockerfile
Docker build working locally but failing in openshift
> updating docker file

- local-db/init-pg.sql
Script done for create - permission, log, token
- [BVPS-128](https://deloittedigital.atlassian.net/browse/BVPS-128)
- [BVPS-129](https://deloittedigital.atlassian.net/browse/BVPS-129)
- [BVPS-147](https://deloittedigital.atlassian.net/browse/BVPS-147)
> add table - permission, log, token

- local-db/init-pg.sql
Database user table modification
> Database user table

- src/data-source.ts
Attempting to fix a weird import error in Openshift. This doesn't occur locally, so I need to merge to test it.
> migration fix?

- src/build/routes.ts
- src/controllers/PropertiesController.ts
- src/routes/index.ts
- src/routes/pins.ts
- src/tests/helpers/geocodeAPICaller.spec.ts
Fixes a casing error that is failing a build...
> fixed casing

- .github/workflows/dev-pipeline.yml
- .github/workflows/npm-test-only-pipeline.yml
- .github/workflows/prod-pipeline.yml
- .github/workflows/test-pipeline.yml
- src/data-source.ts
- src/entity/ActivePin.ts
- src/entity/Employee.ts
- src/entity/PinAuditLog.ts
- src/migration/1693322911755-migration.ts
This contains the DB refactor, as well as updated db models to match the changes.
Note: DO NOT merge this into dev / OpenShift. Until the APIs are fixed, this WILL break the server. This is why unit tests have been disabled for this branch.
> BVPS-225: DB Refactor

- src/entity/AccessRequest.ts
- src/migration/1694657988999-migration.ts
- src/migration/1694660281384-migration.ts
This pull request contains:
- Adding to new fields in user table [updated entity class and created migration file]
- Creating of new Access request table 
1. create new entity
2. create migration file
- create new table, 
- add trigger for updated_at fields
- add trigger for creating a new user when request status changed to Grated.
> Added new columns for Users table and Added new Access Request table

- package.json
- src/entity/Users.ts
- src/migration/1695134056036-migration.ts
Removing the display name column from the users table and updating the model
> BVPS-252: Remove display name column

- package-lock.json
- package.json
- src/build/routes.ts
- src/build/swagger.json
- src/controllers/pinController.ts
- src/entity/AccessRequest.ts
- src/entity/Users.ts
- src/routes/pins.ts
- src/tests/routes/pins.spec.ts
This PR adds API key verification to the /pins/vhers-create endpoint. Also updates a dependency that github was warning about as a vulnerability.
- Added api key auth to /pins/vhers-create endpoint
- Fixed tests
- Updated @babel/traverse due to github notice
> BVPS-288: Create PIN API key

- src/index.ts
> Exposing the header needed for api key auth

- src/build/swagger.json
- src/controllers/pinController.ts
- src/helpers/types.ts
Fixing api documentation to make better note of the need for the property address
> BVPS-315: Fixing API docs

- src/index.ts
A change made server port required, now this is fixed
> BVPS-316 - Fix server port being required

- src/controllers/pinController.ts
- src/db/ActivePIN.db.ts
- src/helpers/GCNotifyCaller.ts
- src/tests/db/ActivePIN.db.spec.ts
- src/tests/routes/pins.spec.ts
Refactoring code so that if GC Notify Call fails, the API fails and the database is not updated.
> GC-Notify Expire, Regenerate, Create Refactor

- src/db/Users.db.ts
Fixed the deactivation reason not showing up in db
> BVPS-344: Deactivated users table - deactivation reason not showing up (in database or UI)

- .env.local
- src/index.ts
- Added properate staging and uat urls to cors whitelist
> BVPS-377: Whitelist Properate URLs

- src/helpers/auth.ts
- src/helpers/userTokenHelper.ts
- src/tests/commonResponses.ts
- src/tests/helpers/userTokenHelper.spec.ts
This PR adds error checking to userTokenHelper.ts and test coverage for the entire file.
> BVPS-418: userTokenHelper test coverage

- src/db/ActivePIN.db.ts
- src/helpers/GCNotifyCalls.ts
- src/tests/helpers/GCNotifyCalls.spec.ts
https://deloittedigital.atlassian.net/browse/BVPS-361
> Moving expire, create, regenerate GC NOtify code into helper function

- package-lock.json
- src/tests/setupJest.ts
This pr obtains full coverage for the data-source.ts and apiKeyAuth.ts files by fixing the env variables in the test config. Also upgrades axios to 1.6.2 to patch a security vulnerability.
> BVPS-406 & BVPS-419: GitHub env variable related test fixes

- src/controllers/pinController.ts
- src/helpers/types.ts
- src/tests/commonResponses.ts
- src/tests/routes/pins.spec.ts
This pr is for test coverage of pinController.ts.
- Updated code and tests to obtain 100% coverage of pinController.ts
> BVPS-411: pinController tests

- src/tests/commonResponses.ts
- src/tests/routes/properties.spec.ts
This PR adds 100% test coverage to PropertiesController.ts.
> BVPS-409: PropertiesController.ts test coverage

- src/build/routes.ts
- src/build/swagger.json
- src/controllers/AccessRequestController.ts
- src/helpers/types.ts
- src/routes/accessRequest.ts
- src/tests/commonResponses.ts
- src/tests/routes/accessRequest.spec.ts
This PR adds full test coverage to AccessRequestController.ts.
> BVPS-408: Test Coverage for AccessRequestContrloler.ts

- src/build/routes.ts
- src/build/swagger.json
- src/db/Users.db.ts
- src/helpers/types.ts
This PR adds the "updatedAt" column to the response of GET /users, as well as few minor swagger changes
> BVPS-447: Update return from db to include "updatedAt" in getAllUsers

- src/build/routes.ts
- src/build/swagger.json
- src/controllers/AccessRequestController.ts
- src/controllers/UserController.ts
- src/routes/users.ts
- src/tests/commonResponses.ts
- src/tests/routes/users.spec.ts
This PR adds full test coverage to UserController.ts, as well as a few small swagger and log changes.
> BVPS-410: UserController.ts test coverage

- src/helpers/auth.ts
- src/tests/helpers/auth.spec.ts
- src/tests/setupJest.ts
This PR obtains full test coverage of auth.ts.
> BVPS-417: auth.ts test coverage

- src/helpers/GCNotifyCaller.ts
- src/tests/helpers/GCNotifyCaller.spec.ts
This PR obtains full test coverage of GCNotifyCaller.ts
> BVPS-415: GCNotifyCaller.ts test coverage

- src/helpers/GCNotifyCaller.ts
- src/helpers/GCNotifyCalls.ts
- src/tests/commonResponses.ts
- src/tests/helpers/GCNotifyCaller.spec.ts
- src/tests/helpers/GCNotifyCalls.spec.ts
This PR obtains full test coverage of GCNotifyCalls.ts
> BVPS-416: GCNotifyCalls.ts test coverage

- src/data-source.ts
- src/db/VHERSAuditLog.db.ts
- src/helpers/GCNotifyCalls.ts
- src/helpers/types.ts
- src/index.ts
- src/middleware/morgan.ts
- src/middleware/responseLogger.ts
- src/tests/commonResponses.ts
- src/tests/db/VHERSAuditLog.db.spec.ts
This PR adds audit logging for /pins/verify, /pins/vhers-create and /pins/vhers-regenerate.
> BVPS-431: Update Existing VHERS APIs to log Success/Failures in log table.

- src/helpers/GCNotifyCalls.ts
> Fixing loop bound injection

- src/db/AccessRequest.db.ts
- src/helpers/auth.ts
- src/middleware/authentication.ts
- src/tests/commonResponses.ts
- src/tests/helpers/auth.spec.ts
- src/tests/middleware/authentication.spec.ts
- src/tests/routes/accessRequest.spec.ts
This PR fixes the erroneous 200 response received when you have a valid token but are not in the database. It will also automatically update your token once you are in the database, no need to clear your cookies before trying to login again
> BVPS-479 : Fix backend login behaviour

- src/middleware/authentication.ts
> adding comment to trigger qa push

- src/controllers/DashboardController.ts
- src/controllers/PropertiesController.ts
- src/tests/commonResponses.ts
- src/tests/routes/dashboard.spec.ts
- src/tests/routes/properties.spec.ts
This PR checks the 'DASHBOARD' permission in the dashboard endpoint instead of the role. Small changes were also made to logs for consistency.
> BVPS-491: Dashboard permission check

- src/build/routes.ts
- src/build/swagger.json
- src/controllers/pinController.ts
- src/tests/routes/dashboard.spec.ts
- src/tests/routes/pins.spec.ts
- src/tests/setupJest.ts
This PR updates error codes on the verify pin endpoint and related tests / documentation.
> BVPS-483: Update /pins/verify error codes

- package-lock.json
- package.json
Fixing the npm dependency vulnerability issue
> Fixed npm audit vulnerability by removing model generator

- .deployment/prod.deploy.yml
- .github/workflows/prod-pipeline.yml
> Qa -> main

- src/build/routes.ts
- src/build/swagger.json
- src/controllers/pinController.ts
- src/tests/routes/pins.spec.ts
Change error code for /pins/verify from 407 to 410 per Properate request.
> BVPS-515: Change error code from 407 to 410

- src/build/swagger.json
- src/controllers/pinController.ts
- src/db/ActivePIN.db.ts
- src/tests/controllers/pinController.spec.ts
- src/tests/db/ActivePIN.db.spec.ts
- src/tests/routes/pins.spec.ts
- Moving dynamic import to the class instance to prevent a file read on every request
- Moving import threshold checks to the dynamic import check, preventing redundant checks
- Changing the PIN update to a single update rather than batch
- Commenting out console logs that clog up the console on this endpoint
- Unit test updates
> Minor optimizations to vhers-create and regenerate endpoints

- matchWeightsThresholds.json
- src/tests/helpers/GCNotifyCalls.spec.ts
Adjusting thresholds down per request
> Adjusting overall thresholds

- .github/workflows/zap-scan.yml
- openshift/tools/clamav-dc.yaml
- openshift/tools/clamav-deployment.yml
- openshift/tools/metabase-dc.yaml
- openshift/tools/metabase-deployment.yml
- openshift/tools/vhers-scan-dc.yaml
- openshift/tools/vhers-scan-deployment.yml
- src/build/routes.ts
- src/build/swagger.json
- src/controllers/bcscController.ts
- src/helpers/auth.ts
- src/helpers/types.ts
- src/routes/bcsc.ts
> refactor: changed bcsc flow to account for 3rd party fe
